### ISSUE TITLE
missing CKNRM

### ISSUE THREAD

**Issue by pommedeterresautee** [sebastian-hofstaetter/transformer-kernel-ranking#2]
you import CKNRM model but it s missing from the repo.
https://github.com/sebastian-hofstaetter/transformer-kernel-ranking/blob/c69870d4c81f066a5476a3b5f05f2da7fb75dcd5/matchmaker/train.py#L49

**Comment by sebastian-hofstaetter** [comment]
Hi,
Thanks for pointing that out, I forgot to copy it - I added it just now.
Best,
Sebastian
